# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.0.18
maven_group=com.yyz
archives_name=yyzsbackpack
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.5
# Dependencies
fabric_loader_version=0.16.14
fabric_api_version=0.126.0+1.21.5
neoforge_version=21.5.75

curios_version=11.0.1+1.21.5
rei_version=19.0.806
trinkets_version = 3.11.0-1.21.5
cca_version=6.3.1
