modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "yyzsbackpack"
version = "${version}"
displayName = "yyzsbackpack"
authors = "yyz729"
description = '''
Modrinth https://modrinth.com/mod/yyzs-backpack
Github https://github.com/yyz729/yyzsbackpack
'''
#logoFile = ""

[[dependencies.yyzsbackpack]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yyzsbackpack]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,1.21.4)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "yyzsbackpack.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
